In [1]:
import pandas as pd
#from datasets import load_dataset
from factory import create_data_loader
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error

In [4]:
data_loader = create_data_loader('titanic', test_size=0.2, normalize_features = "mean_std", return_extra_info = True, encode_categorical=False)
X_train, X_test, y_train, y_test, extra_info = data_loader.load_data()

titanic df len: 891
survived
0    549
1    342
Name: count, dtype: int64


FileNotFoundError: [Errno 2] No such file or directory: './modelsdefinition/IGTD/results/titanic_igtd_Euclidean_Euclidean/abs/_index.txt'

In [3]:
X_train.shape

(26048, 14)

In [110]:
# Compute the bins based on the training set
bins = np.histogram(X_train["PercentInstallTrades"], bins="auto")[1]
bins

array([-2.05103158, -1.93553863, -1.82004567, -1.70455272, -1.58905977,
       -1.47356682, -1.35807387, -1.24258091, -1.12708796, -1.01159501,
       -0.89610206, -0.7806091 , -0.66511615, -0.5496232 , -0.43413025,
       -0.3186373 , -0.20314434, -0.08765139,  0.02784156,  0.14333451,
        0.25882747,  0.37432042,  0.48981337,  0.60530632,  0.72079927,
        0.83629223,  0.95178518,  1.06727813,  1.18277108,  1.29826404,
        1.41375699,  1.52924994,  1.64474289,  1.76023584,  1.8757288 ,
        1.99122175,  2.1067147 ,  2.22220765,  2.33770061,  2.45319356,
        2.56868651,  2.68417946,  2.79967241,  2.91516537,  3.03065832,
        3.14615127,  3.26164422,  3.37713718])

In [81]:
categorical_columns = []
categorical_dims = {}
for col in X_train.columns[X_train.dtypes == object]:
    print(col, X_train[col].nunique())
    l_enc = LabelEncoder()
    X_train[col] = X_train[col].fillna("Missing")
    X_test[col] = X_test[col].fillna("Missing")
    X_train[col] = l_enc.fit_transform(X_train[col].values)
    X_test[col] = l_enc.transform(X_test[col].values)
    categorical_columns.append(col)
    categorical_dims[col] = len(l_enc.classes_)

ExternalRiskEstimate 40


In [82]:
set(X_train["PercentInstallTrades"].unique())-set(X_test["PercentInstallTrades"].unique())

{-1.5032347317912744,
 2.430942622258645,
 2.779540615655473,
 2.9289397556826855,
 3.0285391823674934,
 3.078338895709898}

In [83]:
set(X_test["PercentInstallTrades"].unique())-set(X_train["PercentInstallTrades"].unique())

{2.5803417622858573, 2.9787394690250895}

In [106]:
le = LabelEncoder()
le.fit(X_train["MSinceMostRecentDelq"])

LabelEncoder()

In [108]:
le.classes_

array(['0.0', '10.0', '11.0', '12.0', '13.0', '14.0', '15.0', '16.0',
       '17.0', '18.0', '19.0', '20.0', '21.0', '22.0', '23.0', '24.0',
       '25.0', '26.0', '27.0', '28.0', '29.0', '30.0', '31.0', '32.0',
       '33.0', '34.0', '35.0', '36.0', '37.0', '38.0', '39.0', '4.0',
       '40.0', '41.0', '42.0', '43.0', '44.0', '45.0', '5.0', '6.0',
       '7.0', '8.0', '9.0', 'nan'], dtype=object)

In [107]:
len(le.classes_)

44

In [98]:
le_dict = dict(zip(le.classes_, le.transform(le.classes_)))
#Retrieve label for a single new item, if item is missing then set value as unknown
le_dict.get("heyaa", '<Unknown>')

'<Unknown>'

In [99]:
le_dict

{'0.0': 0,
 '10.0': 1,
 '11.0': 2,
 '12.0': 3,
 '13.0': 4,
 '14.0': 5,
 '15.0': 6,
 '16.0': 7,
 '17.0': 8,
 '18.0': 9,
 '19.0': 10,
 '20.0': 11,
 '21.0': 12,
 '22.0': 13,
 '23.0': 14,
 '24.0': 15,
 '25.0': 16,
 '26.0': 17,
 '27.0': 18,
 '28.0': 19,
 '29.0': 20,
 '30.0': 21,
 '31.0': 22,
 '32.0': 23,
 '33.0': 24,
 '34.0': 25,
 '35.0': 26,
 '36.0': 27,
 '37.0': 28,
 '38.0': 29,
 '39.0': 30,
 '4.0': 31,
 '40.0': 32,
 '41.0': 33,
 '42.0': 34,
 '43.0': 35,
 '44.0': 36,
 '45.0': 37,
 '5.0': 38,
 '6.0': 39,
 '7.0': 40,
 '8.0': 41,
 '9.0': 42,
 'nan': 43}

In [104]:
le.classes_ = np.append(le.classes_,["yo"])

In [105]:
le.classes_

array(['0.0', '10.0', '11.0', '12.0', '13.0', '14.0', '15.0', '16.0',
       '17.0', '18.0', '19.0', '20.0', '21.0', '22.0', '23.0', '24.0',
       '25.0', '26.0', '27.0', '28.0', '29.0', '30.0', '31.0', '32.0',
       '33.0', '34.0', '35.0', '36.0', '37.0', '38.0', '39.0', '4.0',
       '40.0', '41.0', '42.0', '43.0', '44.0', '45.0', '5.0', '6.0',
       '7.0', '8.0', '9.0', 'nan', 'yo'], dtype=object)

In [ ]:

#Retrieve labels for a Dataframe column:

df[your_col] = df[your_col].apply(lambda x: le_dict.get(x, <unknown_value>))

In [72]:
sum([5, 4, 3, 6, 2, 2, 1, 10])

33

In [66]:
features = [ col for col in X_train.columns if col not in ["target"]] 
cat_idxs = [ i for i, f in enumerate(features) if f in categorical_columns]
cat_dims = [ categorical_dims[f] for i, f in enumerate(features) if f in categorical_columns]
print(cat_dims)
print(cat_emb_dim)
print(cat_idxs)

[44]
[5, 4, 3, 6, 2, 2, 1, 10]
[13]


In [67]:
extra_info

{'cat_col_names': ['PercentInstallTrades'],
 'cat_col_idx': [13],
 'cat_col_unique_vals': [44],
 'num_col_names': ['ExternalRiskEstimate',
  'MSinceOldestTradeOpen',
  'MSinceMostRecentTradeOpen',
  'AverageMInFile',
  'NumSatisfactoryTrades',
  'NumTrades60Ever2DerogPubRec',
  'NumTrades90Ever2DerogPubRec',
  'PercentTradesNeverDelq',
  'MSinceMostRecentDelq',
  'MaxDelq2PublicRecLast12M',
  'MaxDelqEver',
  'NumTotalTrades',
  'NumTradesOpeninLast12M',
  'MSinceMostRecentInqexcl7days',
  'NumInqLast6M',
  'NumInqLast6Mexcl7days',
  'NetFractionRevolvingBurden',
  'NetFractionInstallBurden',
  'NumRevolvingTradesWBalance',
  'NumInstallTradesWBalance',
  'NumBank2NatlTradesWHighUtilization',
  'PercentTradesWBalance'],
 'num_col_idx': [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22],
 'column_ordering': [84,
  29,
  39,
  74,
  22,
  63,
  80,
  46,
  12,
  0,
  97,
  107,
  26,
  18,
  9,
  106,
  10,
  64,
  6,


In [34]:
df_train, df_test = bin_numerical_column(X_train, X_test, ["target"])

[-3.65341747 -3.57963013 -3.50584278 -3.43205544 -3.35826809 -3.28448074
 -3.2106934  -3.13690605 -3.06311871 -2.98933136 -2.91554402 -2.84175667
 -2.76796933 -2.69418198 -2.62039464 -2.54660729 -2.47281995 -2.3990326
 -2.32524525 -2.25145791 -2.17767056 -2.10388322 -2.03009587 -1.95630853
 -1.88252118 -1.80873384 -1.73494649 -1.66115915 -1.5873718  -1.51358446
 -1.43979711 -1.36600977 -1.29222242 -1.21843507 -1.14464773 -1.07086038
 -0.99707304 -0.92328569 -0.84949835 -0.775711   -0.70192366 -0.62813631
 -0.55434897 -0.48056162 -0.40677428 -0.33298693 -0.25919959 -0.18541224
 -0.11162489 -0.03783755  0.0359498   0.10973714  0.18352449  0.25731183
  0.33109918  0.40488652  0.47867387  0.55246121  0.62624856]


In [39]:
(df_test["NumTrades60Ever2DerogPubRec"]=="nan").sum()

0

In [31]:
df_train.dtypes

ExternalRiskEstimate                  float64
MSinceOldestTradeOpen                 float64
MSinceMostRecentTradeOpen             float64
AverageMInFile                        float64
NumSatisfactoryTrades                 float64
NumTrades60Ever2DerogPubRec             int64
NumTrades90Ever2DerogPubRec           float64
PercentTradesNeverDelq                float64
MSinceMostRecentDelq                  float64
MaxDelq2PublicRecLast12M              float64
MaxDelqEver                           float64
NumTotalTrades                        float64
NumTradesOpeninLast12M                 object
PercentInstallTrades                  float64
MSinceMostRecentInqexcl7days          float64
NumInqLast6M                          float64
NumInqLast6Mexcl7days                 float64
NetFractionRevolvingBurden            float64
NetFractionInstallBurden              float64
NumRevolvingTradesWBalance            float64
NumInstallTradesWBalance              float64
NumBank2NatlTradesWHighUtilization

In [20]:
df_train["NumRevolvingTradesWBalance"].unique()

array([-0.27268892, -0.04743586, -0.49794197,  0.62832329,  0.40307024,
        0.17781719,  1.75458855, -2.52521943,  0.85357634, -2.75047248,
        1.30408244, -0.72319502,  1.5293355 ,  1.9798416 ,  1.07882939,
        4.00711906,  2.4303477 ,  2.65560075,  3.10610685,  2.20509465,
        2.8808538 ,  3.55661296,  5.35863737,  3.33135991,  5.80914347,
        4.68287821,  4.90813127,  3.78186601,  6.48490263,  4.45762516,
        5.13338432])

In [21]:
X_train["ExternalRiskEstimate"].unique()

array([-0.44267365,  0.36108255,  0.59748143,  0.07740389,  0.17196345,
       -0.15899499,  0.31380278,  0.97571964,  0.69204099,  0.88116009,
       -0.34811409,  0.78660054, -0.20627476, -0.25355454, -0.39539387,
       -0.01715566, -0.58451298,  0.4556421 ,  0.50292188, -3.61041866,
        0.03012412,  0.64476121, -0.11171521, -0.48995342,  0.12468367,
        0.266523  , -0.06443544,  1.0702792 ,  0.21924322,  0.92843987,
        0.40836233, -0.30083432,  0.83388031,  0.73932076,  0.55020166,
       -0.5372332 , -1.19915007,  1.11755897, -0.63179275,  1.16483875,
        1.02299942,  1.21211853, -1.10459051, -1.48282873, -0.96275119,
       -1.29370962, -1.05731074, -0.82091186, -0.7263523 , -0.67907253,
       -0.91547141, -0.77363208, -1.43554895, -1.01003096, -1.15187029,
       -1.3409894 , -1.24642984, -1.62466805, -0.86819163, -1.57738828])

In [8]:
extra_info

{'cat_col_names': ['MSinceMostRecentInqexcl7days'],
 'cat_col_idx': [14],
 'cat_col_unique_vals': [28],
 'num_col_names': ['ExternalRiskEstimate',
  'MSinceOldestTradeOpen',
  'MSinceMostRecentTradeOpen',
  'AverageMInFile',
  'NumSatisfactoryTrades',
  'NumTrades60Ever2DerogPubRec',
  'NumTrades90Ever2DerogPubRec',
  'PercentTradesNeverDelq',
  'MSinceMostRecentDelq',
  'MaxDelq2PublicRecLast12M',
  'MaxDelqEver',
  'NumTotalTrades',
  'NumTradesOpeninLast12M',
  'PercentInstallTrades',
  'NumInqLast6M',
  'NumInqLast6Mexcl7days',
  'NetFractionRevolvingBurden',
  'NetFractionInstallBurden',
  'NumRevolvingTradesWBalance',
  'NumInstallTradesWBalance',
  'NumBank2NatlTradesWHighUtilization',
  'PercentTradesWBalance'],
 'num_col_idx': [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22],
 'column_ordering': [84,
  29,
  39,
  74,
  22,
  63,
  80,
  46,
  12,
  0,
  97,
  107,
  26,
  18,
  9,
  106,
  10,
  64,
  6,


In [13]:
8367%2

1

In [5]:
import os
os.getcwd()

'./notebooks'

In [6]:
# write X_train to CSV file
X_train.to_csv('X_train.csv', index=False)
# write X_val to CSV file
X_val.to_csv('X_val.csv', index=False)
# write y_train to CSV file
y_train.to_csv('y_train.csv', index=False)
# write y_val to CSV file
y_val.to_csv('y_val.csv', index=False)

In [3]:
df = pd.read_csv("./data/covertype/covtype.data.gz")
len(df)

581011

In [4]:
df = pd.read_csv(
            "./data/heloc/heloc_dataset_v1.csv"
        )
len(df)

10459

In [10]:
cat_cols = df.select_dtypes(include=["object", "category"]).columns
cat_cols

Index(['RiskPerformance'], dtype='object')

In [9]:
df.columns

Index(['RiskPerformance', 'ExternalRiskEstimate', 'MSinceOldestTradeOpen',
       'MSinceMostRecentTradeOpen', 'AverageMInFile', 'NumSatisfactoryTrades',
       'NumTrades60Ever2DerogPubRec', 'NumTrades90Ever2DerogPubRec',
       'PercentTradesNeverDelq', 'MSinceMostRecentDelq',
       'MaxDelq2PublicRecLast12M', 'MaxDelqEver', 'NumTotalTrades',
       'NumTradesOpeninLast12M', 'PercentInstallTrades',
       'MSinceMostRecentInqexcl7days', 'NumInqLast6M', 'NumInqLast6Mexcl7days',
       'NetFractionRevolvingBurden', 'NetFractionInstallBurden',
       'NumRevolvingTradesWBalance', 'NumInstallTradesWBalance',
       'NumBank2NatlTradesWHighUtilization', 'PercentTradesWBalance'],
      dtype='object')

In [5]:
df["5"].unique()

array([5, 2, 1, 7, 3, 6, 4])

In [6]:
cat_cols = df.select_dtypes(include=["object", "category"]).columns
cat_cols

Index([], dtype='object')