In [41]:
import pandas as pd
#from datasets import load_dataset
from factory import create_full_data_loader
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
import numpy as np

In [42]:
from sklearn.datasets import load_iris, fetch_california_housing, load_breast_cancer
from sklearn.model_selection import KFold, StratifiedKFold, train_test_split

In [43]:
data_loader = create_full_data_loader("heloc", test_size=0.2, normalize_features="mean_std", return_extra_info=True, encode_categorical=False)
X, y,  extra_info = data_loader.load_data()

In [44]:
 # Merge X_train and y_train
train = pd.concat([X, y], axis=1)

In [45]:
k_value = 5
kf = StratifiedKFold(n_splits=k_value, shuffle=True, random_state=42)
for fold, (train_idx, val_idx) in enumerate(
kf.split(X,y)):
    train_fold = train.iloc[train_idx]
    val_fold = train.iloc[val_idx]
    print(train_fold["target"].shape)
    print(val_fold["target"].shape)

(8367,)
(2092,)
(8367,)
(2092,)
(8367,)
(2092,)
(8367,)
(2092,)
(8368,)
(2091,)


In [73]:
ds = [i for i in enumerate(kf.split(X,y))]
fold_sizes = [i[1][0].shape[0] for i in ds]
fold_sizes

[8367, 8367, 8367, 8367, 8368]

In [69]:
ds

[(0,
  (array([    0,     1,     2, ..., 10455, 10456, 10457]),
   array([    6,    14,    29, ..., 10448, 10454, 10458]))),
 (1,
  (array([    0,     1,     2, ..., 10456, 10457, 10458]),
   array([    4,    17,    20, ..., 10438, 10447, 10452]))),
 (2,
  (array([    2,     3,     4, ..., 10456, 10457, 10458]),
   array([    0,     1,     5, ..., 10444, 10446, 10450]))),
 (3,
  (array([    0,     1,     2, ..., 10456, 10457, 10458]),
   array([    3,     9,    12, ..., 10440, 10449, 10453]))),
 (4,
  (array([    0,     1,     3, ..., 10453, 10454, 10458]),
   array([    2,     7,     8, ..., 10455, 10456, 10457])))]

In [68]:
ds[0][1][0].shape[0]

8367

In [71]:
ds[1][1][0].shape[0]

8367

In [53]:
[len(i[1]) for i in enumerate(kf.split(X,y))]

[2, 2, 2, 2, 2]

In [28]:
train_idx

array([    0,     1,     3, ..., 10453, 10454, 10458])

In [ ]:
# Loop through each element in the list
for fold_length in self.possible_fold_sizes:
    if fold_length % params["batch_size"] == 1:
        self.logger.debug(
            "Fold size and virtual batch size would cause a problem, so removing one observation"
        )
        # Get a random index from the DataFrame
        random_index = train.sample().index
        # Remove the row with the random index
        train.drop(random_index, inplace=True)
        train.reset_index(drop=True, inplace=True)
        break

In [30]:
def calculate_possible_fold_sizes(n_samples, k):
    base_fold_size = n_samples // k
    extra_samples = n_samples % k

    fold_sizes = [base_fold_size] * k

    for i in range(extra_samples):
        fold_sizes[i] += 1

    possible_train_sizes = set([n_samples - f for f in fold_sizes])
    return list(possible_train_sizes)

In [40]:
X = 101
for i in calculate_possible_fold_sizes(X, 5):
    while i % 10 != 1:
        X -= 1

AttributeError: 'int' object has no attribute 'deepcopy'

In [76]:
calculate_possible_fold_sizes(125224648, 5)

[100179718, 100179719]

In [9]:
train

Unnamed: 0       age          workclass    fnlwgt    education  \
0       -1.731998  0.030671          State-gov -1.063611    Bachelors   
1       -1.731891  0.837109   Self-emp-not-inc -1.008707    Bachelors   
2       -1.731785 -0.042642            Private  0.245079      HS-grad   
3       -1.731678  1.057047            Private  0.425801         11th   
4       -1.731572 -0.775768            Private  1.408176    Bachelors   
...           ...       ...                ...       ...          ...   
32556    1.731572 -0.849080            Private  0.639741   Assoc-acdm   
32557    1.731678  0.103983            Private -0.335433      HS-grad   
32558    1.731785  1.423610            Private -0.358777      HS-grad   
32559    1.731891 -1.215643            Private  0.110960      HS-grad   
32560    1.731998  0.983734       Self-emp-inc  0.929893      HS-grad   

       education-num       marital-status          occupation    relationship  \
0           1.134739        Never-married        Adm-clerical   Not-in-family   
1           1.134739   Married-civ-spouse     Exec-managerial         Husband   
2          -0.420060             Divorced   Handlers-cleaners   Not-in-family   
3          -1.197459   Married-civ-spouse   Handlers-cleaners         Husband   
4           1.134739   Married-civ-spouse      Prof-specialty            Wife   
...              ...                  ...                 ...             ...   
32556       0.746039   Married-civ-spouse        Tech-support            Wife   
32557      -0.420060   Married-civ-spouse   Machine-op-inspct         Husband   
32558      -0.420060              Widowed        Adm-clerical       Unmarried   
32559      -0.420060        Never-married        Adm-clerical       Own-child   
32560      -0.420060   Married-civ-spouse     Exec-managerial            Wife   

         race      sex  capital-gain  capital-loss  hours-per-week  \
0       White     Male      0.148453      -0.21666       -0.035429   
1       White     Male     -0.145920      -0.21666       -2.222153   
2       White     Male     -0.145920      -0.21666       -0.035429   
3       Black     Male     -0.145920      -0.21666       -0.035429   
4       Black   Female     -0.145920      -0.21666       -0.035429   
...       ...      ...           ...           ...             ...   
32556   White   Female     -0.145920      -0.21666       -0.197409   
32557   White     Male     -0.145920      -0.21666       -0.035429   
32558   White   Female     -0.145920      -0.21666       -0.035429   
32559   White     Male     -0.145920      -0.21666       -1.655225   
32560   White   Female      1.888424      -0.21666       -0.035429   

       native-country  target  
0       United-States       0  
1       United-States       0  
2       United-States       0  
3       United-States       0  
4                Cuba       0  
...               ...     ...  
32556   United-States       0  
32557   United-States       1  
32558   United-States       0  
32559   United-States       0  
32560   United-States       1  

[32561 rows x 16 columns]

In [29]:
# Create an empty DataFrame to store dataset summaries
summary_data = pd.DataFrame(columns=['Dataset', 'Total Samples', 'Total Features', 
                                     'Target Type', 'Num Classes', 'Num Categorical', 'Num Numerical'])

# Your data loader loop
loaders = [
    "creditcard",
    "housing",
    "adult",
    "heloc",
    "covertype"
]

for dataset_name in loaders:
    try:
        data_loader = create_data_loader(dataset_name, test_size=0.2, normalize_features="mean_std", return_extra_info=True, encode_categorical=False)
        X_train, X_test, y_train, y_test, extra_info = data_loader.load_data()

        # Calculate additional statistics
        total_samples = X_train.shape[0] + X_test.shape[0]
        total_features = X_train.shape[1]
        
        target_type = 'Classification' if isinstance(y_train.iloc[0], np.int64) else 'Regression'
        num_classes = y_train.nunique() if target_type == 'Classification' else None
        num_categorical = X_train.select_dtypes(include=['object']).shape[1]
        num_numerical = X_train.select_dtypes(include=['number']).shape[1]

        # Append summary to DataFrame
        # Inside the loop, replace the append line with this line:
        summary_data = pd.concat([summary_data, pd.DataFrame([[dataset_name, total_samples, total_features,
                                                       target_type, num_classes, num_categorical, num_numerical]],
                                                     columns=summary_data.columns)], ignore_index=True)

        print("SUCCESS", dataset_name)
    except Exception as e:
        print("FAIL", dataset_name)
        print(repr(e))

# Print aggregated summary
print("\nAggregated Dataset Summary:")
print(summary_data)


SUCCESS creditcard
SUCCESS housing
SUCCESS adult
0 Index([], dtype='object')
SUCCESS heloc
SUCCESS covertype

Aggregated Dataset Summary:
      Dataset Total Samples Total Features     Target Type Num Classes  \
0  creditcard         59720             30  Classification           2   
1     housing         20640              9      Regression        None   
2       adult         32561             14  Classification           2   
3       heloc         10459             24  Classification           2   
4   covertype        581011             54  Classification           7   

  Num Categorical Num Numerical  
0               0            30  
1               0             9  
2               8             6  
3               0            24  
4               0            54  


In [31]:
summary_data.to_csv("summary_data.csv", index = False)

In [32]:
# Convert DataFrame to ASCII table
ascii_table = tabulate(summary_data, headers='keys', tablefmt='fancy_grid')

# Print the ASCII table (for preview)
print(ascii_table)


╒════╤════════════╤═════════════════╤══════════════════╤════════════════╤═══════════════╤═══════════════════╤═════════════════╕
│    │ Dataset    │   Total Samples │   Total Features │ Target Type    │   Num Classes │   Num Categorical │   Num Numerical │
╞════╪════════════╪═════════════════╪══════════════════╪════════════════╪═══════════════╪═══════════════════╪═════════════════╡
│  0 │ creditcard │           59720 │               30 │ Classification │             2 │                 0 │              30 │
├────┼────────────┼─────────────────┼──────────────────┼────────────────┼───────────────┼───────────────────┼─────────────────┤
│  1 │ housing    │           20640 │                9 │ Regression     │               │                 0 │               9 │
├────┼────────────┼─────────────────┼──────────────────┼────────────────┼───────────────┼───────────────────┼─────────────────┤
│  2 │ adult      │           32561 │               14 │ Classification │             2 │               

In [35]:
import pandas as pd
from tabulate import tabulate
from PIL import Image, ImageDraw, ImageFont


# Convert DataFrame to ASCII table
ascii_table = tabulate(summary_data, headers='keys', tablefmt='pretty')


# Create an image with the ASCII table content
font = ImageFont.load_default()
lines = ascii_table.split('\n')
lines[0] = f"\033[1m{lines[0]}\033[0m"  # Make headers bold
line_height = font.getsize(lines[0])[1]  # Use getsize from PIL directly
table_width = max(font.getsize(line)[0] for line in lines)
table_height = len(lines) * line_height
image = Image.new('RGB', (table_width, table_height), color='white')
draw = ImageDraw.Draw(image)

# Draw the ASCII table content onto the image
y_position = 0
for line in lines:
    draw.text((0, y_position), line, font=font, fill='black')
    y_position += line_height

# Save the image as a PNG file
image.save('table.png')

AttributeError: 'ImageFont' object has no attribute 'getsize'

In [2]:
loaders = [
    "creditcard",
    "iris",
    "titanic",
    "bufix",
    "breastcancer",
    "housing",
    "ageconditions",
    "adult",
    "heloc",
    "covertype"]

for i in loaders:
    
    try:
        data_loader = create_data_loader(i, test_size=0.2, normalize_features = "mean_std", return_extra_info = True, encode_categorical=False)
        X_train, X_test, y_train, y_test, extra_info = data_loader.load_data()
        print("SUCCESS",i)
    except Exception as e:
        print("FAIL",i)
        print (repr(e))

In [3]:
for i in loaders:
    
    try:
        data_loader = create_data_loader(i, test_size=0.2, normalize_features = "mean_std", return_extra_info = True, encode_categorical=False)
        X_train, X_test, y_train, y_test, extra_info = data_loader.load_data()
        print("SUCCESS",i)
    except Exception as e:
        print("FAIL",i)
        print (repr(e))

SUCCESS creditcard
SUCCESS iris
titanic df len: 891
survived
0    549
1    342
Name: count, dtype: int64
SUCCESS titanic
SUCCESS bufix
SUCCESS breastcancer
SUCCESS housing
0 Index([], dtype='object')
SUCCESS ageconditions
SUCCESS adult
0 Index([], dtype='object')
SUCCESS heloc
SUCCESS covertype


In [3]:
X_train.shape

(26048, 14)

In [110]:
# Compute the bins based on the training set
bins = np.histogram(X_train["PercentInstallTrades"], bins="auto")[1]
bins

array([-2.05103158, -1.93553863, -1.82004567, -1.70455272, -1.58905977,
       -1.47356682, -1.35807387, -1.24258091, -1.12708796, -1.01159501,
       -0.89610206, -0.7806091 , -0.66511615, -0.5496232 , -0.43413025,
       -0.3186373 , -0.20314434, -0.08765139,  0.02784156,  0.14333451,
        0.25882747,  0.37432042,  0.48981337,  0.60530632,  0.72079927,
        0.83629223,  0.95178518,  1.06727813,  1.18277108,  1.29826404,
        1.41375699,  1.52924994,  1.64474289,  1.76023584,  1.8757288 ,
        1.99122175,  2.1067147 ,  2.22220765,  2.33770061,  2.45319356,
        2.56868651,  2.68417946,  2.79967241,  2.91516537,  3.03065832,
        3.14615127,  3.26164422,  3.37713718])

In [81]:
categorical_columns = []
categorical_dims = {}
for col in X_train.columns[X_train.dtypes == object]:
    print(col, X_train[col].nunique())
    l_enc = LabelEncoder()
    X_train[col] = X_train[col].fillna("Missing")
    X_test[col] = X_test[col].fillna("Missing")
    X_train[col] = l_enc.fit_transform(X_train[col].values)
    X_test[col] = l_enc.transform(X_test[col].values)
    categorical_columns.append(col)
    categorical_dims[col] = len(l_enc.classes_)

ExternalRiskEstimate 40


In [82]:
set(X_train["PercentInstallTrades"].unique())-set(X_test["PercentInstallTrades"].unique())

{-1.5032347317912744,
 2.430942622258645,
 2.779540615655473,
 2.9289397556826855,
 3.0285391823674934,
 3.078338895709898}

In [83]:
set(X_test["PercentInstallTrades"].unique())-set(X_train["PercentInstallTrades"].unique())

{2.5803417622858573, 2.9787394690250895}

In [106]:
le = LabelEncoder()
le.fit(X_train["MSinceMostRecentDelq"])

LabelEncoder()

In [108]:
le.classes_

array(['0.0', '10.0', '11.0', '12.0', '13.0', '14.0', '15.0', '16.0',
       '17.0', '18.0', '19.0', '20.0', '21.0', '22.0', '23.0', '24.0',
       '25.0', '26.0', '27.0', '28.0', '29.0', '30.0', '31.0', '32.0',
       '33.0', '34.0', '35.0', '36.0', '37.0', '38.0', '39.0', '4.0',
       '40.0', '41.0', '42.0', '43.0', '44.0', '45.0', '5.0', '6.0',
       '7.0', '8.0', '9.0', 'nan'], dtype=object)

In [107]:
len(le.classes_)

44

In [98]:
le_dict = dict(zip(le.classes_, le.transform(le.classes_)))
#Retrieve label for a single new item, if item is missing then set value as unknown
le_dict.get("heyaa", '<Unknown>')

'<Unknown>'

In [99]:
le_dict

{'0.0': 0,
 '10.0': 1,
 '11.0': 2,
 '12.0': 3,
 '13.0': 4,
 '14.0': 5,
 '15.0': 6,
 '16.0': 7,
 '17.0': 8,
 '18.0': 9,
 '19.0': 10,
 '20.0': 11,
 '21.0': 12,
 '22.0': 13,
 '23.0': 14,
 '24.0': 15,
 '25.0': 16,
 '26.0': 17,
 '27.0': 18,
 '28.0': 19,
 '29.0': 20,
 '30.0': 21,
 '31.0': 22,
 '32.0': 23,
 '33.0': 24,
 '34.0': 25,
 '35.0': 26,
 '36.0': 27,
 '37.0': 28,
 '38.0': 29,
 '39.0': 30,
 '4.0': 31,
 '40.0': 32,
 '41.0': 33,
 '42.0': 34,
 '43.0': 35,
 '44.0': 36,
 '45.0': 37,
 '5.0': 38,
 '6.0': 39,
 '7.0': 40,
 '8.0': 41,
 '9.0': 42,
 'nan': 43}

In [104]:
le.classes_ = np.append(le.classes_,["yo"])

In [105]:
le.classes_

array(['0.0', '10.0', '11.0', '12.0', '13.0', '14.0', '15.0', '16.0',
       '17.0', '18.0', '19.0', '20.0', '21.0', '22.0', '23.0', '24.0',
       '25.0', '26.0', '27.0', '28.0', '29.0', '30.0', '31.0', '32.0',
       '33.0', '34.0', '35.0', '36.0', '37.0', '38.0', '39.0', '4.0',
       '40.0', '41.0', '42.0', '43.0', '44.0', '45.0', '5.0', '6.0',
       '7.0', '8.0', '9.0', 'nan', 'yo'], dtype=object)

In [ ]:

#Retrieve labels for a Dataframe column:

df[your_col] = df[your_col].apply(lambda x: le_dict.get(x, <unknown_value>))

In [72]:
sum([5, 4, 3, 6, 2, 2, 1, 10])

33

In [66]:
features = [ col for col in X_train.columns if col not in ["target"]] 
cat_idxs = [ i for i, f in enumerate(features) if f in categorical_columns]
cat_dims = [ categorical_dims[f] for i, f in enumerate(features) if f in categorical_columns]
print(cat_dims)
print(cat_emb_dim)
print(cat_idxs)

[44]
[5, 4, 3, 6, 2, 2, 1, 10]
[13]


In [67]:
extra_info

{'cat_col_names': ['PercentInstallTrades'],
 'cat_col_idx': [13],
 'cat_col_unique_vals': [44],
 'num_col_names': ['ExternalRiskEstimate',
  'MSinceOldestTradeOpen',
  'MSinceMostRecentTradeOpen',
  'AverageMInFile',
  'NumSatisfactoryTrades',
  'NumTrades60Ever2DerogPubRec',
  'NumTrades90Ever2DerogPubRec',
  'PercentTradesNeverDelq',
  'MSinceMostRecentDelq',
  'MaxDelq2PublicRecLast12M',
  'MaxDelqEver',
  'NumTotalTrades',
  'NumTradesOpeninLast12M',
  'MSinceMostRecentInqexcl7days',
  'NumInqLast6M',
  'NumInqLast6Mexcl7days',
  'NetFractionRevolvingBurden',
  'NetFractionInstallBurden',
  'NumRevolvingTradesWBalance',
  'NumInstallTradesWBalance',
  'NumBank2NatlTradesWHighUtilization',
  'PercentTradesWBalance'],
 'num_col_idx': [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22],
 'column_ordering': [84,
  29,
  39,
  74,
  22,
  63,
  80,
  46,
  12,
  0,
  97,
  107,
  26,
  18,
  9,
  106,
  10,
  64,
  6,


In [34]:
df_train, df_test = bin_numerical_column(X_train, X_test, ["target"])

[-3.65341747 -3.57963013 -3.50584278 -3.43205544 -3.35826809 -3.28448074
 -3.2106934  -3.13690605 -3.06311871 -2.98933136 -2.91554402 -2.84175667
 -2.76796933 -2.69418198 -2.62039464 -2.54660729 -2.47281995 -2.3990326
 -2.32524525 -2.25145791 -2.17767056 -2.10388322 -2.03009587 -1.95630853
 -1.88252118 -1.80873384 -1.73494649 -1.66115915 -1.5873718  -1.51358446
 -1.43979711 -1.36600977 -1.29222242 -1.21843507 -1.14464773 -1.07086038
 -0.99707304 -0.92328569 -0.84949835 -0.775711   -0.70192366 -0.62813631
 -0.55434897 -0.48056162 -0.40677428 -0.33298693 -0.25919959 -0.18541224
 -0.11162489 -0.03783755  0.0359498   0.10973714  0.18352449  0.25731183
  0.33109918  0.40488652  0.47867387  0.55246121  0.62624856]


In [39]:
(df_test["NumTrades60Ever2DerogPubRec"]=="nan").sum()

0

In [31]:
df_train.dtypes

ExternalRiskEstimate                  float64
MSinceOldestTradeOpen                 float64
MSinceMostRecentTradeOpen             float64
AverageMInFile                        float64
NumSatisfactoryTrades                 float64
NumTrades60Ever2DerogPubRec             int64
NumTrades90Ever2DerogPubRec           float64
PercentTradesNeverDelq                float64
MSinceMostRecentDelq                  float64
MaxDelq2PublicRecLast12M              float64
MaxDelqEver                           float64
NumTotalTrades                        float64
NumTradesOpeninLast12M                 object
PercentInstallTrades                  float64
MSinceMostRecentInqexcl7days          float64
NumInqLast6M                          float64
NumInqLast6Mexcl7days                 float64
NetFractionRevolvingBurden            float64
NetFractionInstallBurden              float64
NumRevolvingTradesWBalance            float64
NumInstallTradesWBalance              float64
NumBank2NatlTradesWHighUtilization

In [20]:
df_train["NumRevolvingTradesWBalance"].unique()

array([-0.27268892, -0.04743586, -0.49794197,  0.62832329,  0.40307024,
        0.17781719,  1.75458855, -2.52521943,  0.85357634, -2.75047248,
        1.30408244, -0.72319502,  1.5293355 ,  1.9798416 ,  1.07882939,
        4.00711906,  2.4303477 ,  2.65560075,  3.10610685,  2.20509465,
        2.8808538 ,  3.55661296,  5.35863737,  3.33135991,  5.80914347,
        4.68287821,  4.90813127,  3.78186601,  6.48490263,  4.45762516,
        5.13338432])

In [21]:
X_train["ExternalRiskEstimate"].unique()

array([-0.44267365,  0.36108255,  0.59748143,  0.07740389,  0.17196345,
       -0.15899499,  0.31380278,  0.97571964,  0.69204099,  0.88116009,
       -0.34811409,  0.78660054, -0.20627476, -0.25355454, -0.39539387,
       -0.01715566, -0.58451298,  0.4556421 ,  0.50292188, -3.61041866,
        0.03012412,  0.64476121, -0.11171521, -0.48995342,  0.12468367,
        0.266523  , -0.06443544,  1.0702792 ,  0.21924322,  0.92843987,
        0.40836233, -0.30083432,  0.83388031,  0.73932076,  0.55020166,
       -0.5372332 , -1.19915007,  1.11755897, -0.63179275,  1.16483875,
        1.02299942,  1.21211853, -1.10459051, -1.48282873, -0.96275119,
       -1.29370962, -1.05731074, -0.82091186, -0.7263523 , -0.67907253,
       -0.91547141, -0.77363208, -1.43554895, -1.01003096, -1.15187029,
       -1.3409894 , -1.24642984, -1.62466805, -0.86819163, -1.57738828])

In [8]:
extra_info

{'cat_col_names': ['MSinceMostRecentInqexcl7days'],
 'cat_col_idx': [14],
 'cat_col_unique_vals': [28],
 'num_col_names': ['ExternalRiskEstimate',
  'MSinceOldestTradeOpen',
  'MSinceMostRecentTradeOpen',
  'AverageMInFile',
  'NumSatisfactoryTrades',
  'NumTrades60Ever2DerogPubRec',
  'NumTrades90Ever2DerogPubRec',
  'PercentTradesNeverDelq',
  'MSinceMostRecentDelq',
  'MaxDelq2PublicRecLast12M',
  'MaxDelqEver',
  'NumTotalTrades',
  'NumTradesOpeninLast12M',
  'PercentInstallTrades',
  'NumInqLast6M',
  'NumInqLast6Mexcl7days',
  'NetFractionRevolvingBurden',
  'NetFractionInstallBurden',
  'NumRevolvingTradesWBalance',
  'NumInstallTradesWBalance',
  'NumBank2NatlTradesWHighUtilization',
  'PercentTradesWBalance'],
 'num_col_idx': [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22],
 'column_ordering': [84,
  29,
  39,
  74,
  22,
  63,
  80,
  46,
  12,
  0,
  97,
  107,
  26,
  18,
  9,
  106,
  10,
  64,
  6,


In [13]:
8367%2

1

In [5]:
import os
os.getcwd()

'./notebooks'

In [6]:
# write X_train to CSV file
X_train.to_csv('X_train.csv', index=False)
# write X_val to CSV file
X_val.to_csv('X_val.csv', index=False)
# write y_train to CSV file
y_train.to_csv('y_train.csv', index=False)
# write y_val to CSV file
y_val.to_csv('y_val.csv', index=False)

In [3]:
df = pd.read_csv("./data/covertype/covtype.data.gz")
len(df)

581011

In [4]:
df = pd.read_csv(
            "./data/heloc/heloc_dataset_v1.csv"
        )
len(df)

10459

In [10]:
cat_cols = df.select_dtypes(include=["object", "category"]).columns
cat_cols

Index(['RiskPerformance'], dtype='object')

In [9]:
df.columns

Index(['RiskPerformance', 'ExternalRiskEstimate', 'MSinceOldestTradeOpen',
       'MSinceMostRecentTradeOpen', 'AverageMInFile', 'NumSatisfactoryTrades',
       'NumTrades60Ever2DerogPubRec', 'NumTrades90Ever2DerogPubRec',
       'PercentTradesNeverDelq', 'MSinceMostRecentDelq',
       'MaxDelq2PublicRecLast12M', 'MaxDelqEver', 'NumTotalTrades',
       'NumTradesOpeninLast12M', 'PercentInstallTrades',
       'MSinceMostRecentInqexcl7days', 'NumInqLast6M', 'NumInqLast6Mexcl7days',
       'NetFractionRevolvingBurden', 'NetFractionInstallBurden',
       'NumRevolvingTradesWBalance', 'NumInstallTradesWBalance',
       'NumBank2NatlTradesWHighUtilization', 'PercentTradesWBalance'],
      dtype='object')

In [5]:
df["5"].unique()

array([5, 2, 1, 7, 3, 6, 4])

In [6]:
cat_cols = df.select_dtypes(include=["object", "category"]).columns
cat_cols

Index([], dtype='object')

In [ ]:
3661

In [4]:
import pandas as pd
import numpy as np

In [89]:

def handle_rogue_batch_size(train, val, batch_size):
    num_rows_to_adjust = 1
    if len(train) % batch_size != 1 and  len(val) % batch_size != 1:
        return train, val
    else:
        num_rows_to_adjust = 0
        for i in range(100):
            print(i)
            if len(train) % batch_size == 1:
                num_rows_to_adjust += 1
                removed_rows = train.iloc[-num_rows_to_adjust:]  # Select rows as a DataFrame
                train = train.iloc[:-num_rows_to_adjust]
                val = pd.concat([val, removed_rows], axis=0)
                print("train c1", train.shape, val.shape)
                
            if len(val) % batch_size == 1:
                num_rows_to_adjust += 1
                removed_rows = val.iloc[-num_rows_to_adjust:]  # Select rows as a DataFrame
                val = val.iloc[:-num_rows_to_adjust]
                train = pd.concat([train, removed_rows], axis=0)
                print("val c1", train.shape, val.shape)
                
            if (len(train) % batch_size != 1) and  (len(val) % batch_size != 1):
                break
        return train, val
        

# Rest of the code remains the same as in previous responses


In [92]:
# Create random seed for reproducibility
np.random.seed(42)

# Dataset specifications
train_rows = 3663
val_rows = 3662
num_features = 15
batch_size = 1831

# Create random data
train_data = np.random.random((train_rows, num_features))
val_data = np.random.random((val_rows, num_features))

# Create DataFrames for train and validation datasets
train_df = pd.DataFrame(train_data)
val_df = pd.DataFrame(val_data)
# Ensure the train and validation lengths meet the rogue batch size condition
train_df, val_df = handle_rogue_batch_size(train_df, val_df, batch_size)

# Print train and val shapes
print("Train and val shapes", train_df.shape, val_df.shape, "batch size", batch_size)

# Display first few rows of train and val datasets
print("\nTrain dataset:")
print(train_df.shape)

print("\nValidation dataset:")
print(val_df.shape)

0
train c1 (3662, 15) (3663, 15)
val c1 (3664, 15) (3661, 15)
Train and val shapes (3664, 15) (3661, 15) batch size 1831

Train dataset:
(3664, 15)

Validation dataset:
(3661, 15)


In [39]:
train_df[:-20]

0         1         2         3         4         5         6   \
0     0.374540  0.950714  0.731994  0.598658  0.156019  0.155995  0.058084   
1     0.183405  0.304242  0.524756  0.431945  0.291229  0.611853  0.139494   
2     0.607545  0.170524  0.065052  0.948886  0.965632  0.808397  0.304614   
3     0.662522  0.311711  0.520068  0.546710  0.184854  0.969585  0.775133   
4     0.388677  0.271349  0.828738  0.356753  0.280935  0.542696  0.140924   
...        ...       ...       ...       ...       ...       ...       ...   
3636  0.813152  0.969383  0.964133  0.299185  0.828774  0.678777  0.800076   
3637  0.913273  0.879336  0.614035  0.511630  0.232888  0.789604  0.008205   
3638  0.330936  0.353945  0.498718  0.362375  0.454118  0.546997  0.128348   
3639  0.358926  0.475456  0.149705  0.156468  0.383943  0.378858  0.883332   
3640  0.110925  0.563846  0.159448  0.930871  0.431567  0.919687  0.205100   

            7         8         9         10        11        12        13  \
0     0.866176  0.601115  0.708073  0.020584  0.969910  0.832443  0.212339   
1     0.292145  0.366362  0.456070  0.785176  0.199674  0.514234  0.592415   
2     0.097672  0.684233  0.440152  0.122038  0.495177  0.034389  0.909320   
3     0.939499  0.894827  0.597900  0.921874  0.088493  0.195983  0.045227   
4     0.802197  0.074551  0.986887  0.772245  0.198716  0.005522  0.815461   
...        ...       ...       ...       ...       ...       ...       ...   
3636  0.846238  0.980279  0.151730  0.769746  0.734154  0.287736  0.392588   
3637  0.462787  0.860551  0.618485  0.635123  0.070707  0.286705  0.673862   
3638  0.180475  0.832511  0.459768  0.355152  0.433882  0.174819  0.239847   
3639  0.033451  0.992855  0.956523  0.542251  0.718758  0.935255  0.251194   
3640  0.694036  0.647592  0.399676  0.898343  0.434802  0.198431  0.976985   

            14  
0     0.181825  
1     0.046450  
2     0.258780  
3     0.325330  
4     0.706857  
...        ...  
3636  0.176758  
3637  0.049617  
3638  0.515524  
3639  0.315631  
3640  0.441481  

[3641 rows x 15 columns]

In [19]:
757+15

772